---
description: Pipeline for TYCHON Endpoint Protection Datasets
processors:
  - set:
      field: event.module
      value: tychon
  - set:
      tag: set_orginal
      copy_from: message
      field: event.original
  - json:
      field: message
      add_to_root: true
      add_to_root_conflict_strategy: replace
      tag: convert_json
  - dot_expander:
      tag: expand_dots
      field: '*'
      override: true
  - remove:
      if: ctx.windows_defender.service.nis.signature_last_update == ''
      field: windows_defender.service.nis.signature_last_update
      tag: remove_nis_lupdate
      ignore_failure: true
  - remove:
      if: ctx.windows_defender.service.antivirus.signature_last_update == ''
      field: windows_defender.service.antivirus.signature_last_update
      tag: remove_av_lupdate
      ignore_failure: true
  - remove:
      if: ctx.windows_defender.service.antispyware.signature_last_update == ''
      field: windows_defender.service.antispyware.signature_last_update
      tag: remove_av_lupdate
      ignore_failure: true
  - remove:
      if: ctx.windows_defender.service.antivirus.signature_last_updated == ''
      field: windows_defender.service.antivirus.signature_last_updated
      tag: remove_av_lupdate
      ignore_failure: true
  - remove:
      if: ctx.windows_defender.service.antispyware.signature_last_updated == ''
      field: windows_defender.service.antispyware.signature_last_updated
      tag: remove_av_lupdate
      ignore_failure: true
  - convert:
      field: windows_defender.service.nis.signature_age
      type: long
      ignore_missing: true
  - convert:
      field: windows_defender.service.antivirus.signature_age
      type: long
      ignore_missing: true
  - convert:
      field: windows_defender.service.antispyware.signature_age
      type: long
      ignore_missing: true
  - set:
      field: '@timestamp'
      value: '{{_ingest.timestamp}}'
  - set:
      field: event.ingested
      value: '{{_ingest.timestamp}}'
  - date:
      tag: date_timestamp
      field: '@timestamp'
      formats:
        - ISO8601
  - set:
      field: ecs.version
      value: 8.10.0
  - set:
      field: event.kind
      value: state
  - set:
      field: event.category
      value: [configuration]
  - set:
      field: event.type
      value: [info]
  - remove:
      field: message
      ignore_missing: true
  - remove:
      tag: remove_preserve_original_event
      field: event.original
      if: ctx.tags == null || !(ctx.tags.contains('preserve_original_event'))
      ignore_failure: true
      ignore_missing: true
on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
