---
description: Pipeline for TYCHON Features Datasets
processors:
  - set:
      field: event.module
      value: tychon
  - set:
      tag: set_orginal
      copy_from: message
      field: event.original
  - json:
      field: message
      add_to_root: true
      add_to_root_conflict_strategy: replace
      tag: convert_json
  - dot_expander:
      tag: expand_dots
      field: '*'
      override: true
  - remove:
      field: file.created
      if: ctx.file.created == ''
      tag: remove_file_created
      ignore_failure: true
      ignore_missing: true
  - remove:
      field: file.accessed
      if: ctx.file.accessed == ''
      tag: remove_file_accessed
      ignore_failure: true
      ignore_missing: true
  - remove:
      field: file.mtime
      if: ctx.file.mtime == ''
      tag: remove_file_mtime
      ignore_failure: true
      ignore_missing: true
  - rename:
      field: "server.ip"
      target_field: tychon.server.ip
      ignore_missing: true
      tag: server_ip_rename
  - rename:
      field: "process.information_source"
      target_field: tychon.process.information_source
      ignore_missing: true
      tag: process_infosource_rename
  - rename:
      field: "process.description"
      target_field: tychon.process.description
      ignore_missing: true
      tag: process_description_rename
  - rename:
      field: "process.owner"
      target_field: process.user.name
      ignore_missing: true
      tag: process_owner_rename
  - rename:
      field: "process.ppid"
      target_field: process.parent.pid
      ignore_missing: true
      tag: process_ppid_rename
  - rename:
      field: "service.description"
      target_field: tychon.service.description
      ignore_missing: true
      tag: process_servicedesc_rename
  - rename:
      field: "service.display_name"
      target_field: tychon.service.display_name
      ignore_missing: true
      tag: process_servicedn_rename
  - rename:
      field: "file.code_signature.issuer"
      target_field: file.x509.issuer.distinguished_name
      ignore_missing: true
      tag: file_codesigiss_rename
  - rename:
      field: "file.code_signature.issuer_name"
      target_field: tychon.file.code_signature.issuer_name
      ignore_missing: true
      tag: file_codesigin_rename
  - rename:
      field: "file.code_signature.thumbprint"
      target_field: tychon.file.code_signature.thumbprint
      ignore_missing: true
      tag: file_codesigthumb_rename
  - rename:
      field: "file.code_signature.subject_name"
      target_field: tychon.file.code_signature.subject_name
      ignore_missing: true
      tag: file_codesigsubname_rename
  - rename:
      field: "tls.server.supported_cipher.name"
      target_field: tls.server.supported_ciphers
      ignore_missing: true
      tag: tls_svrscn_rename
  - rename:
      field: "tls.server.supported_cipher.mac"
      target_field: tychon.tls.server.supported_cipher_mac
      ignore_missing: true
      tag: tls_svrscm_rename
  - rename:
      field: "tls.server.cipher.weight"
      target_field: tychon.tls.server.cipher.weight
      ignore_missing: true
      tag: tls_cipherweight_rename
  - rename:
      field: "file.code_signature.friendly_name"
      target_field: tychon.file.code_signature.friendly_name
      ignore_missing: true
      tag: file_csfn_rename
  - rename:
      field: "tls.server.protocol.weight"
      target_field: tychon.tls.server.protocol.weight
      ignore_missing: true
      tag: tls_protoweight_rename
  - rename:
      field: "tls.server.cipher.is_nist_approved"
      target_field: tychon.tls.server.cipher.is_nist_approved
      ignore_missing: true
      tag: tls_nistappr_rename
  - rename:
      field: "tls.server.signature_hash.weight"
      target_field: tychon.tls.server.signature_hash.weight
      ignore_missing: true
      tag: tls_svr_sighash_rename
  - rename:
      field: "connection.state"
      target_field: tychon.connection.state
      ignore_missing: true
      tag: tls_connstate_rename
  - split:
      field: "tls.client.supported_ciphers"
      separator: ","
      ignore_missing: true
      tag: tls_supportedciphers_split
      ignore_failure: true
  - set:
      field: '@timestamp'
      value: '{{_ingest.timestamp}}'
  - set:
      field: event.ingested
      value: '{{_ingest.timestamp}}'
  - date:
      tag: date_timestamp
      field: '@timestamp'
      formats:
        - ISO8601
  - set:
      field: ecs.version
      value: 8.11.0
  - set:
      field: event.kind
      value: state
  - gsub:
      field: host.mac
      pattern: ':'
      replacement: '-'
      ignore_missing: true
  - split:
      field: host.ip
      separator: ','
      ignore_missing: true
      tag: hostipsplit
  - split:
      field: host.ipv4
      separator: ','
      ignore_missing: true
  - convert:
      field: host.uptime
      type: string
      ignore_missing: true
  - set:
      field: host.uptime
      value: '0'
      ignore_failure: true
      if: ctx.host.uptime == ''
  - split:
      field: host.uptime
      separator: '\.+'
      target_field: tempuptime
      ignore_failure: true
  - set:
      field: host.uptime
      value: '{{{tempuptime.0}}}'
      ignore_failure: true
  - remove:
      field: tempuptime
      ignore_failure: true
      ignore_missing: true
  - convert:
      tag: convert_host_uptime
      field: host.uptime
      type: long
      ignore_missing: true
  - set:
      field: event.category
      value: [configuration]
  - set:
      field: event.type
      value: [info]
  - convert:
      field: script.current_duration
      type: string
      ignore_missing: true
  - split:
      field: script.current_duration
      separator: '\.+'
      target_field: tempduration
      ignore_failure: true
  - set:
      field: script.current_duration
      value: '{{{tempduration.0}}}'
      ignore_failure: true
  - remove:
      field: tempduration
      ignore_failure: true
      ignore_missing: true
  - convert:
      tag: convert_script_current_duration
      field: script.current_duration
      type: long
      ignore_missing: true
  - remove:
      field: message
      ignore_missing: true
  - remove:
      tag: remove_preserve_original_event
      field: event.original
      if: ctx.tags == null || !(ctx.tags.contains('preserve_original_event'))
      ignore_failure: true
      ignore_missing: true
on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
