---
description: Pipeline for TYCHON STIG Response Data
processors:
  - set:
      field: ecs.version
      value: 8.11.0
  - set:
      field: event.kind
      value: state
  - set:
      field: event.category
      value: [vulnerability, configuration]
  - set:
      field: event.type
      value: [info]
  - remove:
      tag: remove_preserve_original_event
      field: event.original
      if: ctx.tags == null || !(ctx.tags.contains('preserve_original_event'))
      ignore_failure: true
      ignore_missing: true
  - set:
      if: "ctx.containsKey('rule') && ctx.rule.containsKey('test_result')"
      field: rule.result
      value: '{{rule.test_result}}'
  - remove:
      if: "ctx.containsKey('rule') && ctx.rule.containsKey('test_result')"
      field: rule.test_result
  - convert:
      field: rule.weight
      type: float
      ignore_missing: true
  - remove:
      field: message
      ignore_missing: true
on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
