---
description: Pipeline for CyberArk PAS audit, wrapper
processors:

  - pipeline:
      name: '{{ IngestPipeline "audit" }}'
      if: |
        !ctx.message.contains('"Product":"VaultMonitor"')

on_failure:
  - append:
      field: error.message
      value: '{{{_ingest.on_failure_message}}}'
  - set:
      field: event.kind
      value: pipeline_error
