---
description: Pipeline for TYCHON HOST OS
processors:
  - set:
      field: event.module
      value: tychon
  - set:
      tag: set_orginal
      copy_from: message
      field: original
  - json:
      field: message
      add_to_root: true
      add_to_root_conflict_strategy: replace
      tag: convert_json
  - dot_expander:
      tag: expand_dots
      field: '*'
      override: true
  - set:
      field: ecs.version
      value: 8.10.0
  - set:
      field: event.kind
      value: state
  - convert:
      tag: convert_host_risk_calculated_score
      field: host.risk.calculated_score
      type: float
      ignore_missing: true
  - set:
      field: event.category
      value: [host]
  - set:
      field: event.type
      value: [info]
  - remove:
      tag: remove_preserve_original_event
      field: original
      if: ctx.tags == null || !(ctx.tags.contains('preserve_original_event'))
      ignore_failure: true
      ignore_missing: true
  - set:
      field: host.security.antivirus.exists
      value: 'false'
      if: ctx.host.security.antivirus.exists == ''
  - lowercase:
      field: host.security.antivirus.exists
  - split:
      field: host.security.antivirus.exists
      separator: ','
      target_field: tempav
  - set:
      field: host.security.antivirus.exists
      value: '{{tempav.0}}'
  - remove:
      field: tempav
  - remove:
      field: tychon.definition.oval
      if: ctx.tychon.definition.oval == ''
  - remove:
      field: tychon.definition.stig
      if: ctx.tychon.definition.stig == ''
  - convert:
      field: host.memory.size
      type: long
      ignore_failure: true
  - remove:
      field: message
      ignore_missing: true
on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
