---
description: Pipeline for Hardware
processors:

  - pipeline:
      name: '{{ IngestPipeline "common_init" }}'
  - pipeline:
      name: '{{ IngestPipeline "common_host" }}'
  - pipeline:
      name: '{{ IngestPipeline "rest" }}'

###################
# Failure handler #
###################

on_failure:
  - append:
      field: error.message
      value: >
        Processor "{{{ _ingest.on_failure_processor_type }}}"
        with tag "{{{ _ingest.on_failure_processor_tag }}}"
        in pipeline "{{{ _ingest.on_failure_pipeline }}}"
        failed with message "{{{ _ingest.on_failure_message }}}"
  - set:
      field: event.kind
      value: pipeline_error
