---
description: Pipeline for TYCHON Browser Tables
processors:
    - set:
        field: event.module
        value: tychon
    - set:
        tag: set_orginal
        copy_from: message
        field: event.original
    - json:
        field: message
        target_field: tychon
        tag: convert_json
    - dot_expander:
        tag: expand_dots
        field: '*'
        path: tychon
    - set:
        field: '@timestamp'
        value: '{{_ingest.timestamp}}'
    - set:
        field: event.ingested
        value: '{{_ingest.timestamp}}'
    - date:
        tag: date_timestamp
        field: '@timestamp'
        formats:
        - ISO8601
    - set:
        field: ecs.version
        value: 8.11.0
    - set:
        field: event.kind
        value: state
    - rename:
        field: tychon.package.architecture
        target_field: package.architecture
        ignore_missing: true
        ignore_failure: true
        tag: rename_package_architecture
    - rename:
        field: tychon.package.path
        target_field: package.path
        ignore_missing: true
        ignore_failure: true
        tag: rename_package_path
    - rename:
        field: tychon.host.type
        target_field: host.type
        ignore_missing: true
        ignore_failure: true
        tag: rename_host_type
    - rename:
        field: tychon.package.installed
        target_field: package.installed
        ignore_missing: true
        ignore_failure: true
        tag: rename_package_installed
    - rename:
        field: tychon.tls.version_protocol
        target_field: tls.version_protocol
        ignore_missing: true
        ignore_failure: true
        tag: rename_tls_version_protocol
    - rename:
        field: tychon.host.os.family
        target_field: host.os.family
        ignore_missing: true
        ignore_failure: true
        tag: rename_host_os_family
    - rename:
        field: tychon.package.name
        target_field: package.name
        ignore_missing: true
        ignore_failure: true
        tag: rename_package_name
    - rename:
        field: tychon.package.size
        target_field: package.size
        ignore_missing: true
        ignore_failure: true
        tag: rename_package_size
    - remove:
        field: package.size
        if: ctx.package.size == ""
        ignore_missing: true
    - convert:
        field: package.size
        type: long
        ignore_missing: true
        tag: package_size_convert
    - rename:
        field: tychon.package.version
        target_field: package.version
        ignore_missing: true
        ignore_failure: true
        tag: rename_package_version
    - rename:
        field: tychon.package.type
        target_field: package.type
        ignore_missing: true
        ignore_failure: true
        tag: rename_package_type
    - set:
        field: event.category
        value: [network]
    - set:
        field: event.type
        value: [info]
    - convert:
        field: tychon.script.current_duration
        type: string
        ignore_missing: true
    - split:
        field: tychon.script.current_duration
        separator: '\.+'
        target_field: tempduration
        ignore_failure: true
    - set:
        field: tychon.script.current_duration
        value: '{{{tempduration.0}}}'
        ignore_failure: true
    - remove:
        field: tempduration
        ignore_failure: true
        ignore_missing: true
    - convert:
        tag: convert_script_current_duration
        field: tychon.script.current_duration
        type: long
        ignore_missing: true
    - remove:
        field: message
        ignore_missing: true
    - remove:
        tag: remove_preserve_original_event
        field: event.original
        if: ctx.tags == null || !(ctx.tags.contains('preserve_original_event'))
        ignore_failure: true
        ignore_missing: true
on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
