---
description: Pipeline for the TYCHON Hard Drive Dataset
processors:
  - set:
      field: event.module
      value: tychon
  - set:
      tag: set_orginal
      copy_from: message
      field: event.original
  - json:
      field: message
      add_to_root: true
      add_to_root_conflict_strategy: replace
      tag: convert_json
  - dot_expander:
      tag: expand_dots
      field: '*'
      override: true
  - set:
      field: '@timestamp'
      value: '{{_ingest.timestamp}}'
  - set:
      field: event.ingested
      value: '{{_ingest.timestamp}}'
  - date:
      tag: date_timestamp
      field: '@timestamp'
      formats:
        - ISO8601
  - set:
      field: ecs.version
      value: 8.10.0
  - set:
      field: event.kind
      value: state
  - set:
      field: event.category
      value: [configuration]
  - set:
      field: event.type
      value: [info]
  - convert:
      field: script.current_duration
      type: string
      ignore_missing: true
  - split:
      field: script.current_duration
      separator: '\.+'
      target_field: tempduration
      ignore_failure: true
  - set:
      field: script.current_duration
      value: '{{{tempduration.0}}}'
      ignore_failure: true
  - remove:
      field: tempduration
      ignore_failure: true
      ignore_missing: true
  - convert:
      tag: convert_script_current_duration
      field: script.current_duration
      type: long
      ignore_missing: true
  - remove:
      tag: remove_preserve_original_event
      field: event.original
      if: ctx.tags == null || !(ctx.tags.contains('preserve_original_event'))
      ignore_failure: true
      ignore_missing: true
  - remove:
      field: message
      ignore_missing: true
  - convert:
      field: disk.size
      type: long
      ignore_missing: true
on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
