---
description: Pipeline for TYCHON CPU Information
processors:
  - set:
      field: ecs.version
      value: 8.10.0
  - set:
      field: event.kind
      value: state
  - set:
      field: event.category
      value: [configuration]
  - set:
      field: event.type
      value: [info]
  - gsub:
      field: host.cpu.speed
      pattern: '[^0-9]'
      replacement: ''
  - convert:
      field: host.cpu.speed
      type: long
      ignore_missing: true
  - gsub:
      field: host.cpu.clockspeed
      pattern: '[^0-9]'
      replacement: ''
  - convert:
      field: host.cpu.clockspeed
      type: long
      ignore_missing: true
  - remove:
      field: message
      ignore_missing: true
  - remove:
      tag: remove_preserve_original_event
      field: event.original
      if: ctx.tags == null || !(ctx.tags.contains('preserve_original_event'))
      ignore_failure: true
      ignore_missing: true
on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
